// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180214091100_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<int>("InStock");

                    b.Property<bool>("IsMostLiked");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("ProductSorterID");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductSorterID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication1.Data.Models.ProductSorter", b =>
                {
                    b.Property<int>("ProductSorterID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ProductSorterID");

                    b.ToTable("ProductSorters");
                });

            modelBuilder.Entity("WebApplication1.Data.Models.Product", b =>
                {
                    b.HasOne("WebApplication1.Data.Models.ProductSorter", "ProductSorter")
                        .WithMany("Products")
                        .HasForeignKey("ProductSorterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
